base_url = "https://simplesnap.de"
title = "simplesnap.de"
compile_sass = false
build_search_index = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
theme = "photography"

[extra]
copyright = "simplesnap.de"
footer_links = [
    {url = "https://codeberg.org/arbs09/photography-theme", name = "Theme"},
]
nav_links = [
    {url = "/posts", name = "Posts"},
    {url = "/blog", name = "Blog"},
]
home_links = [
    {url = "/posts", name = "Posts"},
    {url = "/blog", name = "Blog"},
]
no_ai = true
tracking_js = '<script defer src="https://analytics.getroot.eu/script.js" data-website-id="623ad390-6854-43a5-979f-849a077ef368" data-do-not-track="true"></script>'